services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  restaurant-service:
    build:
      context: .
      dockerfile: restaurant-service/Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "8001:8000"

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    ports:
      - "8002:8000"

volumes:
  postgres_data:
